author: yanm1ng # 作者
description: yanm1ng's blog
keyword: hexo-theme, vuejs
favicon: 

excerpt_link: Read more

menu:
 Home: /
 Tags: /tags/
 Archives: /archives/
 Projects: /project/
 About: /about/

# highlight
highlight:
  tomorrow

# catalog
catalog: true

# donate
donate: true

# qrcode
qrcode: true

# comment
# you can set gitment, uyan or disqus

comment: gitment

# gitment config
gitment_owner: yanm1ng
gitment_repo: yanm1ng.github.io
gitment_oauth_id: 0f87e490e00ee3fd87ef
gitment_oauth_secret: 4a9d2b148e7971c2201ad12131ce8bf8159ccd2e

# uyan config
# if you want to use uyan as your blog comment, plz remove/comment out gitment config
baidu_id: 
google_analytics:
# disqus config
disqus_shortname: 

about:
  banner: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1587480809701&di=68eb8a0c6235b7bd338dabb3c3108dc3&imgtype=0&src=http%3A%2F%2Fbpic.588ku.com%2Fback_pic%2F05%2F09%2F61%2F1659866d3f5d229.jpg
  avatar: https://avatars2.githubusercontent.com/u/15856614?s=400&u=3502a2d9db6a2c147091f94fd21dd5afb57af097&v=4
  description: "让我停下脚步的不是我所看见的，而是我所没有看见的"
  github_username: afuryboy

# MathJax Support
mathjax:
  enable: true
  per_page: false
  cdn: //cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config=TeX-AMS-MML_HTMLorMML
